// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucPmrSgE60nql5vV1rLUEYRWy9D29Mn8',
    appId: '1:217867596767:web:b7364b28802b3fe979ca6a',
    messagingSenderId: '217867596767',
    projectId: 'quizmaster-ccl-app-2026',
    authDomain: 'quizmaster-ccl-app-2026.firebaseapp.com',
    storageBucket: 'quizmaster-ccl-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGRff_HlJoEKhiweLyG3zIvAELL291SI',
    appId: '1:217867596767:android:0f9b2265cea04ab379ca6a',
    messagingSenderId: '217867596767',
    projectId: 'quizmaster-ccl-app-2026',
    storageBucket: 'quizmaster-ccl-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMI_NxBP1KSHXJLg6-1zV_7VxVF-dj0Vc',
    appId: '1:217867596767:ios:d37e38a77e6c814279ca6a',
    messagingSenderId: '217867596767',
    projectId: 'quizmaster-ccl-app-2026',
    storageBucket: 'quizmaster-ccl-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
